channels:
  - anaconda
  - pytorch
  - nvidia
  - robostack-staging
dependencies:
  - numpy
  - opencv
  - ultralytics
  - scipy
  - ros-noetic-librealsense2
  - ros-noetic-realsense2-camera
  - ros-noetic-jsk-recognition-msgs
  - ros-noetic-pcl-conversions
  - ros-noetic-pcl-ros
  - pytorch::pytorch # Might need pip
  - pytorch::torchvision # Might need pip
  - pytorch::torchaudio # Might need pip
  - nvidia::pytorch-cuda=11.8 # Might need pip